version: '3.2'

services:
  fast-api-auth:
    build: ./dependencies
    ports:
      - "80:80"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mariadb
    volumes:
      - ./mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=true
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
      start_period: 3s
      start_interval: 3s
      interval: 3s
      timeout: 3s
      retries: 3