version: '3.2'

services:
  wrk:
    image: loadimpact/loadgentest-wrk
    entrypoint: [ "wrk", "-t100", "-c100", "-d60s", "http://module-auth:80/users/login/user1" ]
    depends_on:
      module-auth:
        condition: service_healthy
  redis_host:
    image: redis:latest
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=pass
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
  db_1:
    image: mariadb
    volumes:
      - ./mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3406:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=true
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
      start_period: 1s
      start_interval: 1s
      interval: 1s
      timeout: 1s
      retries: 20

  db_2:
    image: mariadb
    volumes:
      - ./mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3506:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=true
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
      start_period: 1s
      start_interval: 1s
      interval: 1s
      timeout: 1s
      retries: 20

  proxysql:
    image: proxysql/proxysql:2.0.6
    volumes:
      - "./proxysql/proxysql.cnf:/etc/proxysql.cnf"
    ports:
      - "6033:6033"
      - "6032:6032"
    healthcheck:
      test: [ "CMD", "proxysql", "ping", "-h", "127.0.0.1", "-P", "6032", "-u", "root", "-proot" ]
      interval: 1s
      timeout: 1s
      retries: 20
    depends_on:
      db_1:
        condition: service_healthy
      db_2:
        condition: service_healthy

  module-auth:
    build: ./dependencies
    entrypoint: [ "uvicorn", "user_service_controller:app", "--host", "0.0.0.0", "--port", "80" ]
    ports:
      - "80:80"
    healthcheck:
      test: [ "CMD", "curl", "http://module-auth:80/users/login/user1" ]
      interval: 1s
      timeout: 1s
      retries: 20
    depends_on:
      proxysql:
        condition: service_healthy
      redis_host:
        condition: service_healthy

  module-group-chat:
    build: ./dependencies
    entrypoint: [ "uvicorn", "group_chat_service_controller:app", "--host", "0.0.0.0", "--port", "81" ]
    ports:
      - "81:81"
    depends_on:
      proxysql:
        condition: service_healthy
      redis_host:
        condition: service_healthy

  module-ptp-chat:
    build: ./dependencies
    entrypoint: [ "uvicorn", "ptp_chat_service_controller:app", "--host", "0.0.0.0", "--port", "82" ]
    ports:
      - "82:82"
    depends_on:
      proxysql:
        condition: service_healthy
      redis_host:
        condition: service_healthy


