version: '3.2'

services:
  db:
    image: mariadb
    volumes:
      - ./mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=true
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
      start_period: 2s
      start_interval: 2s
      interval: 2s
      timeout: 2s
      retries: 5
  module-auth:
    build: ./dependencies
    entrypoint: ["uvicorn", "user_service_controller:app", "--host", "0.0.0.0", "--port", "80"]
    ports:
      - "80:80"
    depends_on:
      db:
        condition: service_healthy
  module-group-chat:
    build: ./dependencies
    entrypoint: [ "uvicorn", "group_chat_service_controller:app", "--host", "0.0.0.0", "--port", "81" ]
    ports:
      - "81:81"
    depends_on:
      db:
        condition: service_healthy
  module-ptp-chat:
    build: ./dependencies
    entrypoint: [ "uvicorn", "ptp_chat_service_controller:app", "--host", "0.0.0.0", "--port", "82" ]
    ports:
      - "82:82"
    depends_on:
      db:
        condition: service_healthy